### ISSUE TITLE
implement highlight.js

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [Luca-Castelnuovo/test#3]
https://highlightjs.org/

**Comment by Luca-Castelnuovo** [comment]
use https://ace.c9.i

**Comment by CamoBrie** [comment]
cdn: <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/go.min.js"></script>

**Comment by CamoBrie** [comment]
how to use: https://github.com/isagalaev/highlight.js/blob/master/README.md

**Comment by Luca-Castelnuovo** [comment]
deze kan niet met <textarea>

**Comment by CamoBrie** [comment]
kom in call ik laat het je zien

**Comment by Luca-Castelnuovo** [comment]
he brian wil jij een paar mogelijkheden uitproberen en de beste implementenren?

**Comment by Luca-Castelnuovo** [comment]
sort of implemented code mirror
